package org.tensorflow.lite.examples.detection;

public enum Face {
    CHARGING_CHARGING, CHARGING_DECIDING, CHARGING_DISMOUNTING, CHARGING_MOUNTING, CHARGING_SEARCHING,
    MATE_APPROACHING, MATE_DECIDING, MATE_FLEEING, MATE_SEARCHING, NORMAL, MATE_WAITING
}
